### ISSUE TITLE
Research & support us subpage intro module

### ISSUE THREAD

**Issue by Workshop2** [CancerVaccine/cancervaccine.github.io#65]
Need sorting out

**Comment by jazbinda** [comment]
Research section page 8 & 11
Support us section page 16
[CVI 8092016.pdf](https://github.com/CancerVaccine/cancervaccine.github.io/files/461332/CVI.8092016.pdf)

**Comment by jazbinda** [comment]
![image](https://cloud.githubusercontent.com/assets/19264436/18352734/7c5b089a-75d7-11e6-80e5-01e4c9ebe374.png)

**Comment by marusiaa** [comment]
We updated the Support Us and Our Research pages to have the links to other pages in the same category. The images still need resizing to fit in the div correctly.

It's probably best to create a new thumb nail instead of using the existing images on the top of the page.

For the Support Us pages, the description needs to be manually updated using Cloud Cannon. :cake:
